#!/usr/bin/env python3
"""Generate and validate optimized WebP assets used by the research pages."""

from __future__ import annotations

import argparse
import hashlib
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml
from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
PROJECTS_PATH = ROOT / "_data" / "research_projects.yml"
BLOGS_PATH = ROOT / "_data" / "research_project_blogs.yml"
MANIFEST_PATH = ROOT / "_data" / "optimized_images.yml"

PROFILE_IMAGE = "/images/profile.png"
PROGRAM_OVERVIEW = "/images/research/cognitive-neuroscience-overview-en.png"
KIB = 1024
MIB = 1024 * KIB


@dataclass(frozen=True)
class ImageRule:
    category: str
    max_width: int
    quality: int
    budget_bytes: int
    lossless: bool = False


RULES = {
    "profile": ImageRule("profile", 960, 92, 160 * KIB),
    "teaser": ImageRule("teaser", 1600, 100, 250 * KIB),
    "overview": ImageRule("overview", 1600, 95, 250 * KIB),
    "figure": ImageRule("figure", 2400, 100, 800 * KIB, lossless=True),
}


def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or []


def source_path(public_path: str) -> Path:
    return ROOT / public_path.lstrip("/")


def optimized_public_path(public_path: str) -> str:
    relative = Path(public_path.lstrip("/")).relative_to("images")
    target = Path("/images/optimized") / relative.with_suffix(".webp")
    return target.as_posix()


def rule_for(public_path: str, category: str) -> ImageRule:
    if public_path == PROFILE_IMAGE:
        return RULES["profile"]
    if public_path == PROGRAM_OVERVIEW:
        return RULES["overview"]
    if category == "teaser" or Path(public_path).stem.endswith("-teaser"):
        return RULES["teaser"]
    return RULES["figure"]


def collect_assets():
    projects = load_yaml(PROJECTS_PATH)
    blogs = load_yaml(BLOGS_PATH)
    projects_by_id = {project["id"]: project for project in projects}

    assets = {
        PROFILE_IMAGE: "profile",
        PROGRAM_OVERVIEW: "overview",
    }
    for project in projects:
        teaser = project.get("teaser")
        if teaser:
            assets[teaser] = "teaser"

    for blog in blogs:
        project = projects_by_id.get(blog.get("id"))
        if project and project.get("teaser"):
            assets[project["teaser"]] = "teaser"
        for section in blog.get("narrative_sections", []):
            figure = section.get("figure") or section.get("image")
            if figure:
                assets.setdefault(figure, "figure")
            for panel in section.get("panels", []):
                if panel.get("image"):
                    assets.setdefault(panel["image"], "figure")

    return dict(sorted(assets.items())), projects, blogs


def resize_image(image: Image.Image, max_width: int) -> Image.Image:
    if image.width <= max_width:
        return image.copy()
    height = round(image.height * max_width / image.width)
    return image.resize((max_width, height), Image.Resampling.LANCZOS)


def write_asset(public_path: str, category: str):
    source = source_path(public_path)
    if not source.exists():
        raise FileNotFoundError(f"Missing source image: {public_path}")

    rule = rule_for(public_path, category)
    output_public = optimized_public_path(public_path)
    output = source_path(output_public)
    output.parent.mkdir(parents=True, exist_ok=True)

    with Image.open(source) as opened:
        image = ImageOps.exif_transpose(opened)
        image = resize_image(image, rule.max_width)
        if image.mode not in {"RGB", "RGBA"}:
            image = image.convert("RGBA" if "transparency" in image.info else "RGB")
        save_options = {
            "format": "WEBP",
            "method": 6,
        }
        if rule.lossless:
            save_options["lossless"] = True
        else:
            save_options["quality"] = rule.quality
        if opened.info.get("icc_profile"):
            save_options["icc_profile"] = opened.info["icc_profile"]
        image.save(output, **save_options)
        width, height = image.size

    digest = hashlib.sha256(output.read_bytes()).hexdigest()[:12]
    return {
        "webp": output_public,
        "digest": digest,
        "width": width,
        "height": height,
        "bytes": output.stat().st_size,
        "category": rule.category,
        "quality": rule.quality,
        "lossless": rule.lossless,
    }


def write_manifest(manifest):
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    with MANIFEST_PATH.open("w", encoding="utf-8") as handle:
        handle.write("# Generated by scripts/optimize_images.py --write\n")
        yaml.safe_dump(manifest, handle, sort_keys=True, allow_unicode=False)


def validate_manifest(expected_assets, projects, blogs):
    errors = []
    if not MANIFEST_PATH.exists():
        return [f"Missing manifest: {MANIFEST_PATH.relative_to(ROOT)}"]

    manifest = load_yaml(MANIFEST_PATH)
    expected = set(expected_assets)
    actual = set(manifest)
    for missing in sorted(expected - actual):
        errors.append(f"Manifest is missing {missing}")
    for stale in sorted(actual - expected):
        errors.append(f"Manifest contains inactive image {stale}")

    for public_path, category in expected_assets.items():
        source = source_path(public_path)
        if not source.exists():
            errors.append(f"Missing source image {public_path}")
            continue
        entry = manifest.get(public_path)
        if not entry:
            continue
        optimized = source_path(entry.get("webp", ""))
        if not optimized.exists():
            errors.append(f"Missing optimized image for {public_path}")
            continue
        rule = rule_for(public_path, category)
        actual_bytes = optimized.stat().st_size
        if actual_bytes > rule.budget_bytes:
            errors.append(
                f"{entry['webp']} is {actual_bytes / KIB:.0f} KiB; "
                f"budget is {rule.budget_bytes / KIB:.0f} KiB"
            )
        if entry.get("bytes") != actual_bytes:
            errors.append(f"Manifest byte count is stale for {entry['webp']}")
        actual_digest = hashlib.sha256(optimized.read_bytes()).hexdigest()[:12]
        if entry.get("digest") != actual_digest:
            errors.append(f"Manifest digest is stale for {entry['webp']}")
        try:
            with Image.open(optimized) as image:
                if image.format != "WEBP":
                    errors.append(f"{entry['webp']} is not WebP")
                if [image.width, image.height] != [entry.get("width"), entry.get("height")]:
                    errors.append(f"Manifest dimensions are stale for {entry['webp']}")
        except OSError as exc:
            errors.append(f"Cannot read {entry['webp']}: {exc}")

    if errors:
        return errors

    def optimized_size(public_path):
        return source_path(manifest[public_path]["webp"]).stat().st_size

    home_assets = [PROFILE_IMAGE]
    home_assets.extend(
        project["teaser"]
        for project in projects
        if project.get("show_on_homepage") and project.get("teaser")
    )
    home_total = sum(optimized_size(path) for path in dict.fromkeys(home_assets))
    if home_total > 1.25 * MIB:
        errors.append(f"Homepage image total is {home_total / MIB:.2f} MiB; budget is 1.25 MiB")
    if optimized_size(PROFILE_IMAGE) > 200 * KIB:
        errors.append("Homepage critical image budget exceeds 200 KiB")

    projects_by_id = {project["id"]: project for project in projects}
    for blog in blogs:
        project = projects_by_id.get(blog.get("id"))
        if not project:
            continue
        page_assets = [project["teaser"]]
        for section in blog.get("narrative_sections", []):
            figure = section.get("figure") or section.get("image")
            if figure:
                page_assets.append(figure)
            page_assets.extend(
                panel["image"] for panel in section.get("panels", []) if panel.get("image")
            )
        page_assets = list(dict.fromkeys(page_assets))
        page_total = sum(optimized_size(path) for path in page_assets)
        if optimized_size(project["teaser"]) > 250 * KIB:
            errors.append(f"{blog['id']} critical image budget exceeds 250 KiB")
        if page_total > 1.6 * MIB:
            errors.append(
                f"{blog['id']} image total is {page_total / MIB:.2f} MiB; budget is 1.6 MiB"
            )

    return errors


def print_summary(expected_assets, projects, blogs):
    manifest = load_yaml(MANIFEST_PATH)

    def size(public_path):
        return source_path(manifest[public_path]["webp"]).stat().st_size

    original_total = sum(source_path(path).stat().st_size for path in expected_assets)
    optimized_total = sum(size(path) for path in expected_assets)
    print(
        f"Optimized {len(expected_assets)} active images: "
        f"{original_total / MIB:.2f} MiB -> {optimized_total / MIB:.2f} MiB "
        f"({100 * optimized_total / original_total:.1f}%)"
    )

    home_assets = [PROFILE_IMAGE]
    home_assets.extend(
        project["teaser"]
        for project in projects
        if project.get("show_on_homepage") and project.get("teaser")
    )
    print(f"Homepage full image payload: {sum(size(p) for p in dict.fromkeys(home_assets)) / KIB:.0f} KiB")

    projects_by_id = {project["id"]: project for project in projects}
    for blog in blogs:
        project = projects_by_id.get(blog.get("id"))
        if not project:
            continue
        page_assets = [project["teaser"]]
        for section in blog.get("narrative_sections", []):
            figure = section.get("figure") or section.get("image")
            if figure:
                page_assets.append(figure)
            page_assets.extend(
                panel["image"] for panel in section.get("panels", []) if panel.get("image")
            )
        page_assets = list(dict.fromkeys(page_assets))
        print(f"{blog['id']} full image payload: {sum(size(p) for p in page_assets) / KIB:.0f} KiB")


def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Generate WebP assets and manifest")
    mode.add_argument("--check", action="store_true", help="Validate committed optimized assets")
    args = parser.parse_args()

    expected_assets, projects, blogs = collect_assets()
    if args.write:
        manifest = {
            public_path: write_asset(public_path, category)
            for public_path, category in expected_assets.items()
        }
        write_manifest(manifest)

    errors = validate_manifest(expected_assets, projects, blogs)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print_summary(expected_assets, projects, blogs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
